on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    runs-on: ubuntu-latest
    env:
      ONIGMO_VERSION: 6.2.0
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Install onigmo
      run: make install-onigmo

    - name: Test
      run: go test ./...
